[tox]
requires =
    tox-uv
envlist =
    py313-django{52,51}
    py3{12,11,10}-django{52,51,50,42}
    py39-django42
    lint

[testenv]
deps =
    django52: django>=5.2,<6
    django51: django>=5.1,<5.2
    django50: django>=5.0,<5.1
    django42: django>=4.2,<5

dependency_groups = dev

commands = pytest tests --cov=bitcaster_django --cov-report=xml --junitxml {toxworkdir}{/}junit-{envname}.xml -o junit_family=legacy {posargs:tests}

[testenv:lint]
deps =
    mypy
    ruff

commands =
    ruff check src
    mypy src
