# Generated by Django 5.2 on 2025-05-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("local_name", models.CharField(max_length=100, unique=True)),
                ("remote_event_slug", models.SlugField(max_length=100)),
            ],
        ),
    ]
