# Generated by Django 5.1.3 on 2025-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("local_name", models.CharField(unique=True)),
                ("remote_event_slug", models.SlugField()),
            ],
        ),
    ]
