# Generated by Django 5.2 on 2025-05-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="EventConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("local_name", models.CharField(unique=True)),
                ("remote_event_slug", models.SlugField()),
            ],
        ),
    ]
