# Generated by Django 6.0.7 on 2026-08-07 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster_django", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventConfig",
        ),
    ]
